services:
  transaction-server:
    build: ./transaction-server/
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    read_only: true
    init: true
    command: --bind :8080
