services:
  db:
    image: mongo:6
    read_only: true
    init: true
    volumes:
      - type: tmpfs
        target: /tmp

  redis: 
    container_name: redisCache
    image: redis
    init: true
    ports:
      - "6379:6379"

  transaction-server:
    build: ./transaction-server/
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    depends_on:
      - redis
      - db
    read_only: true
    init: true
    command: --bind :8080
    environment:
      DATABASE_URI: mongodb://db/?directConnection=true
      

  build-test:
    build: ./testing/
    links: 
      - transaction-server
