services:
  db:
    image: mongo:6
    read_only: true
    init: true
    volumes:
      - type: tmpfs
        target: /tmp

  transaction-server:
    build: ./transaction-server/
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    read_only: true
    depends_on:
      - db
    init: true
    command: --bind :8080
    environment:
      DATABASE_URI: mongodb://db/?directConnection=true
      

  build-test:
    build: ./testing/
    links: 
      - transaction-server
