services:
  db:
    image: mongo:6
    read_only: true
    init: true
    volumes:
      - type: tmpfs
        target: /tmp

  redis:
    container_name: redisCache
    image: redis
    init: true
    ports:
      - "6379:6379"

  polling_microservice:
    build:
      context: ./
      dockerfile: polling_service/Dockerfile
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    command: --bind :8081
    depends_on:
      - redis
      - quote_server
    environment:
      QUOTE_SERVER: quote_server:4444

  transaction-server:
    build:
      context: ./
      dockerfile: transaction-server/Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    depends_on:
      - redis
      - db
      - polling_microservice
    read_only: true
    init: true
    command: --bind :8080
    environment:
      DATABASE_URI: mongodb://db/?directConnection=true
      POLLING_SERVICE: http://polling_microservice:8081

  quote_server:
    build: ./quote_server
    ports:
      - target: 4444
        published: 4444
        protocol: tcp
    command: --bind :4444


  #build-test:
  #  build: ./testing/
  #  links:
  #    - transaction-server
