# The valid `Host` header values for this app. Prevents DNS rebinding attacks even when running without a reverse proxy.
allowed_hosts = ["daytrading.localhost"]

# The valid `Origin` header values for browser POST requests. Like `allowed_hosts`, but an entire origin, so includes scheme and port number if non-standard.
csrf_allowed_origins = ["http://daytrading.localhost:8000"]

# Whether to serve static files. Disable when behind a reverse proxy and use a separate (or its) static file server to reduce attack surface.
serve_static_files = true

# The connecting IP addresses for which to trust `X-Forwarded-For` and `X-Forwarded-Proto` headers.
proxy_trusted_hosts = []  # when never behind a reverse proxy
#proxy_trusted_hosts = ["*"]  # when always behind a reverse proxy, e.g. production

[sessions]
# The 16-byte urlbase64-encoded secret keys for encrypting and signing sessions. The first key is used for new sessions and to refresh sessions using other keys.
# Generate with `secrets.token_urlsafe(16)` and make sure a new key is rolled out to all web servers before making it the key in use.
secret_keys = [
	"3pDtBH5a3Dt-pb5HVSCnwQ",
]

# The cookie name. Should start with `__Host-` prefix in production.
cookie_name = "s"

# Whether to set the `Secure` flag on cookies. Should be true in production.
cookie_secure = false

# Hard expiry of a session even if refreshed.
max_lifetime_minutes = 60

# A session with no activity in this many minutes expires.
timeout_minutes = 5
